export const ticketActionTypes={
    SET_SELECTED_GOAL:"SET_SELECTED_GOAL",
    SET_MESSAGE_GOAL:"SET_MESSAGE_GOAL",
    SET_RECIEVED_SNOOZED:"SET_RECIEVED_SNOOZED",
    SET_CHAT_MESSAGES:"SET_CHAT_MESSAGES"
}